In [1]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta
import plotly.express as px
from IPython.display import HTML
from IPython.display import Image
import warnings
warnings.filterwarnings('ignore')

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'

# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
# sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp", spark_submit="spark3-submit")
 
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-08-14 18:20:43 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/mmm_tdc/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

# Introducción

Pueden aparecer nuevos errores que no habían sido tenidos en cuenta en el momento en que se creo el archivo *distribucion_frecuencia_errores_experiencia_tdc_20240101_20260804.xlsx*, por tanto se debe marcar manualmente con la ayuda de **Karla Cristina Arboleda Alvarez**, DISEÑADOR/A PROCESOS - LDC FC TRANSFORMACION DIGITAL [equipo Fernando Jose Arias Mora, DUEÑO/A PRODUCTO - LDC FC MERCADEO DE TECNOLOGIA]

In [38]:
# Leer archivo distribucion frecuencia errores bloqueantes experiencia digital tdc que se tenga hasta el momento
df_dist_errores_old = pd.read_excel('hist_data/distribucion_frecuencia_errores_experiencia_tdc_20240101_20260804.xlsx')
df_dist_errores_old

,nombre_experiencia,codigo_experiencia,codigo_error,descripcion_tecnica_error,descripcion_funcional_error,servicio_error,operacion_error,tipo_error,categoria_error,cantidad_registros,error_bloqueante
0,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,19256,0
1,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,9387,0
2,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,NaN,NaN,NaN,DEFAULT,True,8557,0
3,preaprobado_comportamental,180,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,7715,0
4,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,NaN,NaN,NaN,DEFAULT,True,7510,0
...,...,...,...,...,...,...,...,...,...,...,...
395,preaprobado_comportamental,180,12-297,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
396,preaprobado_mastercard_joven,10,923,Transacción rechazada por validación de fraude,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
397,motor_mastercard_joven,110,TC_007,El consumo al servicio retrieveContactInfoPpal...,NaN,NaN,NaN,DEFAULT,True,1,0
398,preaprobado_mastercard_negocios,21,AUT000,CannotCreateTransactionException Could not ope...,"¡Ups! Algo falló. Lo sentimos, estamos trabaja...",AW1316001_VTDAPIAutenticacion,authorize,TECHNICAL,True,1,1
399,motor_mastercard_joven,110,TC_009,El consumo al servicio retrieveDetaildInformat...,NaN,NaN,NaN,DEFAULT,True,1,0

In [39]:
df_dist_errores_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   nombre_experiencia           400 non-null    object
 1   codigo_experiencia           400 non-null    int64
 2   codigo_error                 400 non-null    object
 3   descripcion_tecnica_error    338 non-null    object
 4   descripcion_funcional_error  242 non-null    object
 5   servicio_error               242 non-null    object
 6   operacion_error              242 non-null    object
 7   tipo_error                   400 non-null    object
 8   categoria_error              400 non-null    bool
 9   cantidad_registros           400 non-null    int64
 10  error_bloqueante             400 non-null    int64
dtypes: bool(1), int64(3), object(7)
memory usage: 31.8+ KB

In [40]:
# Convertir valores perdidos a cadena vacía en el dataframe df_dist_errores_old
df_dist_errores_old = df_dist_errores_old.fillna('')

In [41]:
# Transformar todas las columnas del dataframe df_dist_errores_old a tipo string
df_dist_errores_old = df_dist_errores_old.astype(str)
df_dist_errores_old.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   nombre_experiencia           400 non-null    object
 1   codigo_experiencia           400 non-null    object
 2   codigo_error                 400 non-null    object
 3   descripcion_tecnica_error    400 non-null    object
 4   descripcion_funcional_error  400 non-null    object
 5   servicio_error               400 non-null    object
 6   operacion_error              400 non-null    object
 7   tipo_error                   400 non-null    object
 8   categoria_error              400 non-null    object
 9   cantidad_registros           400 non-null    object
 10  error_bloqueante             400 non-null    object
dtypes: object(11)
memory usage: 34.5+ KB

In [42]:
df_dist_errores_old

,nombre_experiencia,codigo_experiencia,codigo_error,descripcion_tecnica_error,descripcion_funcional_error,servicio_error,operacion_error,tipo_error,categoria_error,cantidad_registros,error_bloqueante
0,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,19256,0
1,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,9387,0
2,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,8557,0
3,preaprobado_comportamental,180,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,7715,0
4,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,7510,0
...,...,...,...,...,...,...,...,...,...,...,...
395,preaprobado_comportamental,180,12-297,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
396,preaprobado_mastercard_joven,10,923,Transacción rechazada por validación de fraude,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
397,motor_mastercard_joven,110,TC_007,El consumo al servicio retrieveContactInfoPpal...,,,,DEFAULT,True,1,0
398,preaprobado_mastercard_negocios,21,AUT000,CannotCreateTransactionException Could not ope...,"¡Ups! Algo falló. Lo sentimos, estamos trabaja...",AW1316001_VTDAPIAutenticacion,authorize,TECHNICAL,True,1,1
399,motor_mastercard_joven,110,TC_009,El consumo al servicio retrieveDetaildInformat...,,,,DEFAULT,True,1,0

In [44]:
# Obtener nuevamente distribución de erroes bloqueantes experiencia digital tdc con las ingestiones más recientes
sql = """
SELECT nombre_experiencia,
       codigo_experiencia,
       codigo_error,
       descripcion_tecnica_error,
       descripcion_funcional_error,
       servicio_error,
       operacion_error,
       tipo_error,
       categoria_error,
       count(*) AS cantidad_registros
FROM resultados_vspc_canales.fco_logex_vd
WHERE YEAR BETWEEN 2024 AND 2026
  AND MONTH BETWEEN 1 AND 12
  AND DAY BETWEEN 1 AND 31
  AND cast(codigo_experiencia AS int) IN (10, -- preaprobado mc joven
 11, -- preaprobado mc ideal
 12, -- preaprobado multifranquicia
 21, -- mc negocios segm independientes
 180, -- preaprobado comportamental tdc unica virtual
 111, -- motor mc ideal
 110, -- motor mc joven
 112 -- motor multifranquicia
 )
  AND resultado_trx = 'ERROR'
  AND tipo_error NOT IN ('EXCEPCIONNEGOCIO',
                         'BUSINESS',
                         'NEGOCIO',
                         'EXCEPCIONES DE NEGOCIO',
                         'EXCEPCIONSERVICIO',
                         'BUSINESSEXCEPTIONS')
GROUP BY 1,
         2,
         3,
         4,
         5,
         6,
         7,
         8,
         9
ORDER BY count(*) DESC
"""
df_dist_errores_new = helper.obtener_dataframe(sql)
df_dist_errores_new

------------------------------------------------------------
  i    tipo    nombre    estado     hora_inicio   duracion
------------------------------------------------------------
 5/5 DATAFRAME         ejecutando   06:58:57 PM

2026-08-14 18:59:00 - [INFO] - 411 filas, 10 columnas, 00:02.4 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 5/5 DATAFRAME         finalizado   06:58:57 PM     00:02.6
------------------------------------------------------------

,nombre_experiencia,codigo_experiencia,codigo_error,descripcion_tecnica_error,descripcion_funcional_error,servicio_error,operacion_error,tipo_error,categoria_error,cantidad_registros
0,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,19256
1,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,None,None,None,DEFAULT,True,11084
2,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,None,None,None,DEFAULT,True,10470
3,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,9387
4,preaprobado_comportamental,180,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,7715
...,...,...,...,...,...,...,...,...,...,...
406,motor_mastercard_joven,110,AUT015,"BP0382 - Lo sentimos, tenemos problemas con nu...",Ocurrió un error al refrescar la sesión,Customer Contact Session - Management,keepAlive,TECHNICAL,True,1
407,preaprobado_comportamental,180,SEG_002,"Error de seguridad, franquicia o categoria sel...",None,None,None,DEFAULT,True,1
408,preaprobado_multifranquicia,12,AUT007,NotFound 404 Not Found from POST https://gw-se...,Ocurrió un error al leer la respuesta de uno d...,Session Authorization - Access Token Management,generateByAuthorizationCode,TECHNICAL,True,1
409,preaprobado_multifranquicia,12,TC_009,El consumo al servicio retrieveDetaildInformat...,None,None,None,DEFAULT,True,1
410,motor_mastercard_ideal,111,APIC_903,El cliente no cumple con el rol 01 ni 02 por l...,None,None,None,DEFAULT,True,1

In [45]:
# Convertir valores perdidos a cadena vacía en el dataframe df_dist_errores_new
df_dist_errores_new = df_dist_errores_new.fillna('')

In [46]:
# Transformar todas las columnas del dataframe df_dist_errores_new a tipo string
df_dist_errores_new = df_dist_errores_new.astype(str)
df_dist_errores_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   nombre_experiencia           411 non-null    object
 1   codigo_experiencia           411 non-null    object
 2   codigo_error                 411 non-null    object
 3   descripcion_tecnica_error    411 non-null    object
 4   descripcion_funcional_error  411 non-null    object
 5   servicio_error               411 non-null    object
 6   operacion_error              411 non-null    object
 7   tipo_error                   411 non-null    object
 8   categoria_error              411 non-null    object
 9   cantidad_registros           411 non-null    object
dtypes: object(10)
memory usage: 32.2+ KB

In [47]:
df_dist_errores_old

,nombre_experiencia,codigo_experiencia,codigo_error,descripcion_tecnica_error,descripcion_funcional_error,servicio_error,operacion_error,tipo_error,categoria_error,cantidad_registros,error_bloqueante
0,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,19256,0
1,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,9387,0
2,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,8557,0
3,preaprobado_comportamental,180,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,7715,0
4,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,7510,0
...,...,...,...,...,...,...,...,...,...,...,...
395,preaprobado_comportamental,180,12-297,Sin Informacion,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
396,preaprobado_mastercard_joven,10,923,Transacción rechazada por validación de fraude,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,1,0
397,motor_mastercard_joven,110,TC_007,El consumo al servicio retrieveContactInfoPpal...,,,,DEFAULT,True,1,0
398,preaprobado_mastercard_negocios,21,AUT000,CannotCreateTransactionException Could not ope...,"¡Ups! Algo falló. Lo sentimos, estamos trabaja...",AW1316001_VTDAPIAutenticacion,authorize,TECHNICAL,True,1,1
399,motor_mastercard_joven,110,TC_009,El consumo al servicio retrieveDetaildInformat...,,,,DEFAULT,True,1,0

In [48]:
# Crear una columna adicional que se llame "llave_error" que sea la concatenación de las columnas nombre_experiencia, codigo_experiencia, codigo_error, descripcion_tecnica_error, descripcion_funcional_error, servicio_error, operacion_error, tipo_error y categoria_error
df_dist_errores_old['llave_error'] = df_dist_errores_old['nombre_experiencia'] + '_' + df_dist_errores_old['codigo_experiencia'] + '_' + df_dist_errores_old['codigo_error'] + '_' + df_dist_errores_old['descripcion_tecnica_error'] + '_' + df_dist_errores_old['descripcion_funcional_error'] + '_' + df_dist_errores_old['servicio_error'] + '_' + df_dist_errores_old['operacion_error'] + '_' + df_dist_errores_old['tipo_error'] + '_' + df_dist_errores_old['categoria_error']
df_dist_errores_new['llave_error'] = df_dist_errores_new['nombre_experiencia'] + '_' + df_dist_errores_new['codigo_experiencia'] + '_' + df_dist_errores_new['codigo_error'] + '_' + df_dist_errores_new['descripcion_tecnica_error'] + '_' + df_dist_errores_new['descripcion_funcional_error'] + '_' + df_dist_errores_new['servicio_error'] + '_' + df_dist_errores_new['operacion_error'] + '_' + df_dist_errores_new['tipo_error'] + '_' + df_dist_errores_new['categoria_error']

In [49]:
# Adicionar la columna "error_bloqueante" del dataframe df_dist_errores_old al dataframe df_dist_errores_new
df_dist_errores_new = df_dist_errores_new.merge(df_dist_errores_old[['llave_error', 'error_bloqueante']], on='llave_error', how='left')
df_dist_errores_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 411 entries, 0 to 410
Data columns (total 12 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   nombre_experiencia           411 non-null    object
 1   codigo_experiencia           411 non-null    object
 2   codigo_error                 411 non-null    object
 3   descripcion_tecnica_error    411 non-null    object
 4   descripcion_funcional_error  411 non-null    object
 5   servicio_error               411 non-null    object
 6   operacion_error              411 non-null    object
 7   tipo_error                   411 non-null    object
 8   categoria_error              411 non-null    object
 9   cantidad_registros           411 non-null    object
 10  llave_error                  411 non-null    object
 11  error_bloqueante             400 non-null    object
dtypes: object(12)
memory usage: 41.7+ KB

In [50]:
df_dist_errores_new

,nombre_experiencia,codigo_experiencia,codigo_error,descripcion_tecnica_error,descripcion_funcional_error,servicio_error,operacion_error,tipo_error,categoria_error,cantidad_registros,llave_error,error_bloqueante
0,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,19256,preaprobado_multifranquicia_12_930_Necesitamos...,0
1,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,11084,motor_multifranquicia_112_930_Necesitamos vali...,0
2,preaprobado_multifranquicia,12,930,Necesitamos validar información adicional. Acé...,,,,DEFAULT,True,10470,preaprobado_multifranquicia_12_930_Necesitamos...,0
3,motor_multifranquicia,112,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,9387,motor_multifranquicia_112_930_Necesitamos vali...,0
4,preaprobado_comportamental,180,930,Necesitamos validar información adicional. Acé...,Sin Informacion,Sin Informacion,Sin Informacion,DEFAULT,True,7715,preaprobado_comportamental_180_930_Necesitamos...,0
...,...,...,...,...,...,...,...,...,...,...,...,...
406,motor_mastercard_joven,110,AUT015,"BP0382 - Lo sentimos, tenemos problemas con nu...",Ocurrió un error al refrescar la sesión,Customer Contact Session - Management,keepAlive,TECHNICAL,True,1,motor_mastercard_joven_110_AUT015_BP0382 - Lo ...,1
407,preaprobado_comportamental,180,SEG_002,"Error de seguridad, franquicia o categoria sel...",,,,DEFAULT,True,1,preaprobado_comportamental_180_SEG_002_Error d...,0
408,preaprobado_multifranquicia,12,AUT007,NotFound 404 Not Found from POST https://gw-se...,Ocurrió un error al leer la respuesta de uno d...,Session Authorization - Access Token Management,generateByAuthorizationCode,TECHNICAL,True,1,preaprobado_multifranquicia_12_AUT007_NotFound...,NaN
409,preaprobado_multifranquicia,12,TC_009,El consumo al servicio retrieveDetaildInformat...,,,,DEFAULT,True,1,preaprobado_multifranquicia_12_TC_009_El consu...,0
410,motor_mastercard_ideal,111,APIC_903,El cliente no cumple con el rol 01 ni 02 por l...,,,,DEFAULT,True,1,motor_mastercard_ideal_111_APIC_903_El cliente...,0

In [51]:
# Escribir a excel el dataframe df_dist_errores_new
df_dist_errores_new.to_excel('hist_data/distribucion_frecuencia_errores_experiencia_tdc_20240101_20260814.xlsx', index=False)